version: '3.7'

services:
  prepperpantry-postgres:
    image: postgres:11.5
    ports:
      - 127.0.0.1:${PORTS__POSTGRES:-5432}:5432
    environment:
      - POSTGRES_USER=${POSTGRES__USER:-prepper}
      - POSTGRES_PASSWORD=${POSTGRES__PASS:-this-is-secure}
      - POSTGRES_DB=${POSTGRES__DB:-prepperpantry}
      - POSTGRES_INITDB_ARGS=--encoding=utf8